- name: Download jwat-tools
  get_url: url=https://bitbucket.org/nclarkekb/jwat-tools/downloads/jwat-tools-{{ jwattools.version }}.tar.gz dest=/tmp/jwat-tools-{{ jwattools.version }}.tar.gz

- name: Uncompress jwat-tools
  unarchive: src=/tmp/jwat-tools-{{ jwattools.version }}.tar.gz dest=/opt/ copy=no owner=root group=root creates=/opt/jwat-tools-{{ jwattools.version }}

- name: Symlink install directory
  file: src=/opt/jwat-tools-{{ jwattools.version }} path=/opt/jwat-tools state=link
