- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  sudo: True

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat.majorversion }}/v{{ tomcat.version }}/bin/apache-tomcat-{{ tomcat.version }}.tar.gz dest=/tmp/apache-tomcat-{{ tomcat.version }}.tar.gz

- name: Uncompress Tomcat
  unarchive: src=/tmp/apache-tomcat-{{ tomcat.version }}.tar.gz dest=/opt/ copy=no owner=root group=root creates=/opt/apache-tomcat-{{ tomcat.version }}

- name: Change ownership of Tomcat installation
  file: path=/opt/apache-tomcat-{{ tomcat.version }} owner=tomcat group=tomcat state=directory recurse=yes

- name: Symlink install directory
  file: src=/opt/apache-tomcat-{{ tomcat.version }} path=/opt/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat systemd config
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service mode=0644 owner=root group=root

- name: reload systemd
  command: /usr/bin/systemctl --system daemon-reload

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port=8080

