- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  sudo: True

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.64/bin/apache-tomcat-7.0.64.tar.gz dest=/tmp/apache-tomcat-7.0.64.tar.gz

- name: Uncompress Tomcat
  unarchive: src=/tmp/apache-tomcat-7.0.64.tar.gz dest=/opt/ copy=no owner=root group=root creates=/opt/apache-tomcat-7.0.64

- name: Change ownership of Tomcat installation
  file: path=/opt/apache-tomcat-7.0.64 owner=tomcat group=tomcat state=directory recurse=yes

- name: Symlink install directory
  file: src=/opt/apache-tomcat-7.0.64 path=/opt/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat systemd config
  copy: src=tomcat.service dest=/lib/systemd/system/tomcat.service mode=0644 owner=root group=root

- name: reload systemd
  command: /usr/bin/systemctl --system daemon-reload

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port=8080

