- name: ensure EPEL repository RPM is enabled
  yum: name=epel-release

- name: ensure some base packages are installed
  yum: name={{ item }} state=present
  with_items:
    - curl
    - vim-common
    - vim-enhanced
    - wget
    - git
    - libselinux-python
    - unzip
    - htop
