- name: Manual Operation Required
  debug: msg="Please compile openwayback from https://github.com/gcwa/openwayback and uncompress into /opt/openwayback"
  
- name: install OpenWayback war
  copy: src=/opt/openwayback/openwayback-{{ openwayback.version }}.war dest=/opt/tomcat/webapps/ROOT.war owner=root group=root mode=644 backup=yes

#- name: clear Tomcat current ROOT app
#  file: path=/opt/tomcat/webapps/ROOT/ state=absent
